import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { openSans, pinyonScript, playFair, roboto } from "@/utils/fonts";
import { TanstackProvider } from "@/providers/tanstack-provider";
import { Footer } from "@/components/main/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${openSans.variable} ${playFair.variable} ${pinyonScript.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <TanstackProvider>{children}</TanstackProvider>
        <Footer />
      </body>
    </html>
  );
}
