import type { Metadata } from "next";
import "../globals.css";
import { openSans, pinyonScript, playFair, roboto } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${openSans.variable} ${playFair.variable} ${pinyonScript.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
