import type { Metadata } from "next";
import "../globals.css";
import { openSans, pinyonScript, playFair, roboto } from "@/utils/fonts";
import { Header } from "@/components/LandingPage/Header";
import { Footer } from "@/components/LandingPage/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${openSans.variable} ${playFair.variable} ${pinyonScript.variable} `}
      >
        <Header />
        <main className="max-w-7xl mx-auto px-6 py-6">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
